In [1]:
import  pandas  as pd
import numpy as np

In [2]:
df = pd.read_csv("IMDB.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [5]:
df.drop_duplicates(inplace = True)

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
#  data preprocessing
#  converting data to lowercase
df["review"] = df["review"].str.lower()

In [8]:
#  url removing from the data

import re
sample_text = "yogesh is a good boy,is it right yogesh"
#  yogesh -> to vivek
new_text =re.sub("yogesh","vivek",sample_text)

In [9]:
new_text

'vivek is a good boy,is it right vivek'

In [10]:
#  removing the url
def remove_urls(text):
    text=  re.sub(r"http\S+","",text)
    return text

df["review"] = df["review"].apply(remove_urls)

In [11]:
#  removing punctutaions
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]","",text)
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [12]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [13]:
#  removing HTML
def remove_html(text):
    text=  re.sub(r"<.*?>","",text)
    return text

df["review"] = df["review"].apply(remove_html)

In [14]:
#  removing the stopword'
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [16]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [17]:
sample_text = "i love coding very much"
tokenize= word_tokenize(sample_text)

In [18]:
tokenize

['i', 'love', 'coding', 'very', 'much']

In [ ]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
           text =  text.replace(word,"")

        return text


df["review"] = df["review"].apply(remove_stopwords)

In [ ]:
df.head()

In [21]:
#  set the stemming
#  running -> run
#  playing -> play
# porter stemming
from  nltk.stem import PorterStemmer

In [22]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []


    tokens = word_tokenize(text)
    for token in tokens:
       stemmed_token =  ps.stem(token)
       stemmed_words.append(stemmed_token)


       return " ".join(stemmed_words)
        
df["review"] = df["review"].apply(stemming)

In [23]:
df.head()

    review sentiment
0      one  positive
1   wonder  positive
2  thought  positive
3    basic  negative
4   petter  positive

In [24]:


# encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

In [25]:
y= df["sentiment"]

In [26]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [27]:
#  vectorization
df.head()

    review  sentiment
0      one          1
1   wonder          1
2  thought          1
3    basic          0
4   petter          1

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf= TfidfVectorizer(max_features = 5000)
X = tf.fit_transform(df["review"])

In [29]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 46834 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3335)	1.0
  (1, 4926)	1.0
  (2, 4674)	1.0
  (3, 271)	1.0
  (4, 3514)	1.0
  (5, 3680)	1.0
  (6, 4587)	1.0
  (7, 4311)	1.0
  (8, 1287)	1.0
  (9, 4971)	1.0
  (10, 3522)	1.0
  (11, 4117)	1.0
  (12, 2173)	1.0
  (13, 464)	1.0
  (15, 2474)	1.0
  (16, 1505)	1.0
  (17, 3052)	1.0
  (18, 3892)	1.0
  (19, 249)	1.0
  (20, 4653)	1.0
  (21, 1883)	1.0
  (22, 171)	1.0
  (23, 1522)	1.0
  (24, 4839)	1.0
  (25, 2432)	1.0
  :	:
  (49554, 3092)	1.0
  (49555, 3052)	1.0
  (49556, 4235)	1.0
  (49557, 1671)	1.0
  (49558, 4693)	1.0
  (49559, 4653)	1.0
  (49561, 4117)	1.0
  (49562, 1085)	1.0
  (49563, 1901)	1.0
  (49564, 4117)	1.0
  (49565, 4556)	1.0
  (49567, 278)	1.0
  (49568, 2705)	1.0
  (49569, 2177)	1.0
  (49570, 3894)	1.0
  (49572, 1803)	1.0
  (49573, 2540)	1.0
  (49574, 2374)	1.0
  (49575, 3986)	1.0
  (49576, 2282)	1.0
  (49577, 4674)	1.0
  (49578, 257)	1.0
  (49579, 163)	1.0
  (49580, 2173)	1.0
  (49581, 3335)	1.0

In [30]:
#  data sets and data loaders
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2,random_state = 42)

In [31]:
X_train = X_train.toarray()
X_test = X_test.toarray()
#  iska matlab 5000 main se 4000 value training set main hain

In [32]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(39665, 5000))

In [33]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [34]:
train_set  = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
    
    
)


test_set  = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
    
    
)

In [ ]:
train_loader =  DataLoader(train_set,shuffle = True,batch_size = 64)
test_loader =  DataLoader(train_set,shuffle = True,batch_size = 64)

In [ ]:
#  BUILD THE RNN
import torch.nn as nn
import torch.optim as optim

In [ ]:
class RNN(nn.Module):
    
    def __init__(self,input_size,hidden_size= 128,num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers


        self.rnn = nn.RNN(input_size,hidden_size,num_layers,batch_first = True)
        #  fcc layers fully conneted layers
        self.fcc= nn.Linear(hidden_size,1)

        


    def forward(self,x):
            h0= torch.zeros(self.num_layers,x.size(0),self.hidden_size)
            out, _ =  self.rnn(x,h0)
            #  1st value  = hidden state of  all time stamps
            #  2nd value  = final hidden state of last timestamps
            out = self.fcc(out[:,-1,:])
            return out

In [ ]:
input_size = X_train.shape[1]
model = RNN(input_size)

criterion  = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

In [ ]:
#  training the rnn
 # unsqueeze 
#  squeeze 
epochs = 10
for epoch in range(epochs):
    model.train()
    

    for Xb,yb in train_loader:
        optimizer.zero_grad()
        Xb = Xb.unsqueeze(1)
    
    #  add singleton direction

    outputs = model(Xb)
    #  batchsize 1

    outputs = torch.sigmoid(outputs.squeeze())
    #  batchsize, probability ayegi
    loss = criterion(outputs,yb)
    #  compute loss
    loss.backward()
    #  backdrop kro
    optimizer.step()
    #  weights update kro

    print(f"epoch = {epoch+1}/{epochs} and loss  {loss.item()}")

In [ ]:
#  evaluate the model
model.eval()


with torch.no_grad():
    correct_value = 0
    tot_vals = 0

    for Xb,yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_value += (predicted == yb).sum().item()

        print(f"accuracy = {correct_value/tot_vals*100}")